spring:
  neo4j:
    uri: ${NEO4J_URI}
    authentication:
      username: ${NEO4J_ID}
      password: ${NEO4J_PW}
  thymeleaf:
    cache: false

logging:
  level:
    org:
      springframework:
        data:
          neo4j: DEBUG

url:
  app: http://localhost:8080